//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Correios.Services.WebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="edeiSoapBinding", Namespace="http://service.edei.correios.com.br/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TO))]
    public partial class edei : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback solicitarSaldoClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback cancelarRotuloUnitizadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarUnitizadorOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarCodigoFaturaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarEncomendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultarRestricaoProibicaoItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback consultaFaturaEntregaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getVersaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarCodigoEtiquetaInternacionalOperationCompleted;
        
        private System.Threading.SendOrPostCallback solicitarRotuloUnitizadorOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public edei() {
            this.Url = global::Correios.Services.Properties.Settings.Default.Correios_Services_WebService_edei;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event solicitarSaldoClienteCompletedEventHandler solicitarSaldoClienteCompleted;
        
        /// <remarks/>
        public event cancelarRotuloUnitizadorCompletedEventHandler cancelarRotuloUnitizadorCompleted;
        
        /// <remarks/>
        public event consultarUnitizadorCompletedEventHandler consultarUnitizadorCompleted;
        
        /// <remarks/>
        public event solicitarCodigoFaturaCompletedEventHandler solicitarCodigoFaturaCompleted;
        
        /// <remarks/>
        public event consultarEncomendaCompletedEventHandler consultarEncomendaCompleted;
        
        /// <remarks/>
        public event consultarRestricaoProibicaoItemCompletedEventHandler consultarRestricaoProibicaoItemCompleted;
        
        /// <remarks/>
        public event consultaFaturaEntregaCompletedEventHandler consultaFaturaEntregaCompleted;
        
        /// <remarks/>
        public event getVersaoCompletedEventHandler getVersaoCompleted;
        
        /// <remarks/>
        public event solicitarCodigoEtiquetaInternacionalCompletedEventHandler solicitarCodigoEtiquetaInternacionalCompleted;
        
        /// <remarks/>
        public event solicitarRotuloUnitizadorCompletedEventHandler solicitarRotuloUnitizadorCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarSaldoCliente", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoSaldo solicitarSaldoCliente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("solicitarSaldoCliente", new object[] {
                        xml});
            return ((RetornoSaldo)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarSaldoClienteAsync(string xml) {
            this.solicitarSaldoClienteAsync(xml, null);
        }
        
        /// <remarks/>
        public void solicitarSaldoClienteAsync(string xml, object userState) {
            if ((this.solicitarSaldoClienteOperationCompleted == null)) {
                this.solicitarSaldoClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarSaldoClienteOperationCompleted);
            }
            this.InvokeAsync("solicitarSaldoCliente", new object[] {
                        xml}, this.solicitarSaldoClienteOperationCompleted, userState);
        }
        
        private void OnsolicitarSaldoClienteOperationCompleted(object arg) {
            if ((this.solicitarSaldoClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarSaldoClienteCompleted(this, new solicitarSaldoClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("cancelarRotuloUnitizador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoCancelarRotuloUnitizador cancelarRotuloUnitizador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("cancelarRotuloUnitizador", new object[] {
                        xml});
            return ((RetornoCancelarRotuloUnitizador)(results[0]));
        }
        
        /// <remarks/>
        public void cancelarRotuloUnitizadorAsync(string xml) {
            this.cancelarRotuloUnitizadorAsync(xml, null);
        }
        
        /// <remarks/>
        public void cancelarRotuloUnitizadorAsync(string xml, object userState) {
            if ((this.cancelarRotuloUnitizadorOperationCompleted == null)) {
                this.cancelarRotuloUnitizadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OncancelarRotuloUnitizadorOperationCompleted);
            }
            this.InvokeAsync("cancelarRotuloUnitizador", new object[] {
                        xml}, this.cancelarRotuloUnitizadorOperationCompleted, userState);
        }
        
        private void OncancelarRotuloUnitizadorOperationCompleted(object arg) {
            if ((this.cancelarRotuloUnitizadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.cancelarRotuloUnitizadorCompleted(this, new cancelarRotuloUnitizadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarUnitizador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoConsultaUnitizador consultarUnitizador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("consultarUnitizador", new object[] {
                        xml});
            return ((RetornoConsultaUnitizador)(results[0]));
        }
        
        /// <remarks/>
        public void consultarUnitizadorAsync(string xml) {
            this.consultarUnitizadorAsync(xml, null);
        }
        
        /// <remarks/>
        public void consultarUnitizadorAsync(string xml, object userState) {
            if ((this.consultarUnitizadorOperationCompleted == null)) {
                this.consultarUnitizadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarUnitizadorOperationCompleted);
            }
            this.InvokeAsync("consultarUnitizador", new object[] {
                        xml}, this.consultarUnitizadorOperationCompleted, userState);
        }
        
        private void OnconsultarUnitizadorOperationCompleted(object arg) {
            if ((this.consultarUnitizadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarUnitizadorCompleted(this, new consultarUnitizadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarCodigoFatura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoCodigoFatura solicitarCodigoFatura([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("solicitarCodigoFatura", new object[] {
                        xml});
            return ((RetornoCodigoFatura)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarCodigoFaturaAsync(string xml) {
            this.solicitarCodigoFaturaAsync(xml, null);
        }
        
        /// <remarks/>
        public void solicitarCodigoFaturaAsync(string xml, object userState) {
            if ((this.solicitarCodigoFaturaOperationCompleted == null)) {
                this.solicitarCodigoFaturaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarCodigoFaturaOperationCompleted);
            }
            this.InvokeAsync("solicitarCodigoFatura", new object[] {
                        xml}, this.solicitarCodigoFaturaOperationCompleted, userState);
        }
        
        private void OnsolicitarCodigoFaturaOperationCompleted(object arg) {
            if ((this.solicitarCodigoFaturaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarCodigoFaturaCompleted(this, new solicitarCodigoFaturaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarEncomenda", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoConsultaEncomenda consultarEncomenda([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("consultarEncomenda", new object[] {
                        xml});
            return ((RetornoConsultaEncomenda)(results[0]));
        }
        
        /// <remarks/>
        public void consultarEncomendaAsync(string xml) {
            this.consultarEncomendaAsync(xml, null);
        }
        
        /// <remarks/>
        public void consultarEncomendaAsync(string xml, object userState) {
            if ((this.consultarEncomendaOperationCompleted == null)) {
                this.consultarEncomendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarEncomendaOperationCompleted);
            }
            this.InvokeAsync("consultarEncomenda", new object[] {
                        xml}, this.consultarEncomendaOperationCompleted, userState);
        }
        
        private void OnconsultarEncomendaOperationCompleted(object arg) {
            if ((this.consultarEncomendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarEncomendaCompleted(this, new consultarEncomendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarRestricaoProibicaoItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoRestricaoProibicao consultarRestricaoProibicaoItem([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("consultarRestricaoProibicaoItem", new object[] {
                        xml});
            return ((RetornoRestricaoProibicao)(results[0]));
        }
        
        /// <remarks/>
        public void consultarRestricaoProibicaoItemAsync(string xml) {
            this.consultarRestricaoProibicaoItemAsync(xml, null);
        }
        
        /// <remarks/>
        public void consultarRestricaoProibicaoItemAsync(string xml, object userState) {
            if ((this.consultarRestricaoProibicaoItemOperationCompleted == null)) {
                this.consultarRestricaoProibicaoItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultarRestricaoProibicaoItemOperationCompleted);
            }
            this.InvokeAsync("consultarRestricaoProibicaoItem", new object[] {
                        xml}, this.consultarRestricaoProibicaoItemOperationCompleted, userState);
        }
        
        private void OnconsultarRestricaoProibicaoItemOperationCompleted(object arg) {
            if ((this.consultarRestricaoProibicaoItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultarRestricaoProibicaoItemCompleted(this, new consultarRestricaoProibicaoItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultaFaturaEntrega", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoConsultaFaturaEntregaTO consultaFaturaEntrega([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("consultaFaturaEntrega", new object[] {
                        xml});
            return ((RetornoConsultaFaturaEntregaTO)(results[0]));
        }
        
        /// <remarks/>
        public void consultaFaturaEntregaAsync(string xml) {
            this.consultaFaturaEntregaAsync(xml, null);
        }
        
        /// <remarks/>
        public void consultaFaturaEntregaAsync(string xml, object userState) {
            if ((this.consultaFaturaEntregaOperationCompleted == null)) {
                this.consultaFaturaEntregaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnconsultaFaturaEntregaOperationCompleted);
            }
            this.InvokeAsync("consultaFaturaEntrega", new object[] {
                        xml}, this.consultaFaturaEntregaOperationCompleted, userState);
        }
        
        private void OnconsultaFaturaEntregaOperationCompleted(object arg) {
            if ((this.consultaFaturaEntregaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.consultaFaturaEntregaCompleted(this, new consultaFaturaEntregaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("versao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getVersao() {
            object[] results = this.Invoke("getVersao", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getVersaoAsync() {
            this.getVersaoAsync(null);
        }
        
        /// <remarks/>
        public void getVersaoAsync(object userState) {
            if ((this.getVersaoOperationCompleted == null)) {
                this.getVersaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetVersaoOperationCompleted);
            }
            this.InvokeAsync("getVersao", new object[0], this.getVersaoOperationCompleted, userState);
        }
        
        private void OngetVersaoOperationCompleted(object arg) {
            if ((this.getVersaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getVersaoCompleted(this, new getVersaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarCodigoEtiquetaInternacional", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoEtiquetaInternacional solicitarCodigoEtiquetaInternacional([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("solicitarCodigoEtiquetaInternacional", new object[] {
                        xml});
            return ((RetornoEtiquetaInternacional)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarCodigoEtiquetaInternacionalAsync(string xml) {
            this.solicitarCodigoEtiquetaInternacionalAsync(xml, null);
        }
        
        /// <remarks/>
        public void solicitarCodigoEtiquetaInternacionalAsync(string xml, object userState) {
            if ((this.solicitarCodigoEtiquetaInternacionalOperationCompleted == null)) {
                this.solicitarCodigoEtiquetaInternacionalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarCodigoEtiquetaInternacionalOperationCompleted);
            }
            this.InvokeAsync("solicitarCodigoEtiquetaInternacional", new object[] {
                        xml}, this.solicitarCodigoEtiquetaInternacionalOperationCompleted, userState);
        }
        
        private void OnsolicitarCodigoEtiquetaInternacionalOperationCompleted(object arg) {
            if ((this.solicitarCodigoEtiquetaInternacionalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarCodigoEtiquetaInternacionalCompleted(this, new solicitarCodigoEtiquetaInternacionalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://service.edei.correios.com.br/", ResponseNamespace="http://service.edei.correios.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("solicitarRotuloUnitizador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public RetornoRotuloUnitizador solicitarRotuloUnitizador([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("solicitarRotuloUnitizador", new object[] {
                        xml});
            return ((RetornoRotuloUnitizador)(results[0]));
        }
        
        /// <remarks/>
        public void solicitarRotuloUnitizadorAsync(string xml) {
            this.solicitarRotuloUnitizadorAsync(xml, null);
        }
        
        /// <remarks/>
        public void solicitarRotuloUnitizadorAsync(string xml, object userState) {
            if ((this.solicitarRotuloUnitizadorOperationCompleted == null)) {
                this.solicitarRotuloUnitizadorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsolicitarRotuloUnitizadorOperationCompleted);
            }
            this.InvokeAsync("solicitarRotuloUnitizador", new object[] {
                        xml}, this.solicitarRotuloUnitizadorOperationCompleted, userState);
        }
        
        private void OnsolicitarRotuloUnitizadorOperationCompleted(object arg) {
            if ((this.solicitarRotuloUnitizadorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.solicitarRotuloUnitizadorCompleted(this, new solicitarRotuloUnitizadorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoSaldo : TO {
        
        private string saldoField;
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class Retorno : AgrupadorRetorno {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Retorno))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorRetorno : TO {
        
        private Ocorrencia[] ocorrenciaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ocorrencia")]
        public Ocorrencia[] ocorrencia {
            get {
                return this.ocorrenciaField;
            }
            set {
                this.ocorrenciaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class Ocorrencia : TO {
        
        private string codigoRetornoField;
        
        private string mensagemRetornoField;
        
        private string descricaoRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoRetorno {
            get {
                return this.codigoRetornoField;
            }
            set {
                this.codigoRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string mensagemRetorno {
            get {
                return this.mensagemRetornoField;
            }
            set {
                this.mensagemRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoRetorno {
            get {
                return this.descricaoRetornoField;
            }
            set {
                this.descricaoRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemRetornoRotuloUnitizador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoRotuloUnitizador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemRetornoEtiquetaInternacional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoEtiquetaInternacional))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorObjetoRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(unitizadorRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorUnitizadorRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(expedicaoRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorExpedicaoRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(faturaEntregaRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorFaturaEntregaRetornoConsulta))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoConsultaFaturaEntregaTO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemRetornoRestricaoProibicao))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoRestricaoProibicao))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemEncomenda))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorItemEncomenda))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemRetornoConsultaEncomenda))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorItemRetornoConsultaEncomenda))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoConsultaEncomenda))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoCodigoFatura))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoConsultaUnitizador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ItemRetornoConsultaUnitizador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoCancelarRotuloUnitizador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Ocorrencia))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AgrupadorRetorno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Retorno))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RetornoSaldo))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public abstract partial class TO {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemRetornoRotuloUnitizador : TO {
        
        private string sequencialField;
        
        private string codigoUnitizadorField;
        
        private Retorno ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sequencial {
            get {
                return this.sequencialField;
            }
            set {
                this.sequencialField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoUnitizador {
            get {
                return this.codigoUnitizadorField;
            }
            set {
                this.codigoUnitizadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoRotuloUnitizador : TO {
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        private ItemRetornoRotuloUnitizador[] itemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoRotuloUnitizador[] itemRetorno {
            get {
                return this.itemRetornoField;
            }
            set {
                this.itemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemRetornoEtiquetaInternacional : TO {
        
        private string numeroEtiquetaObjetoField;
        
        private string codigoControleClienteField;
        
        private Retorno ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroEtiquetaObjeto {
            get {
                return this.numeroEtiquetaObjetoField;
            }
            set {
                this.numeroEtiquetaObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoControleCliente {
            get {
                return this.codigoControleClienteField;
            }
            set {
                this.codigoControleClienteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoEtiquetaInternacional : TO {
        
        private string versaoField;
        
        private Retorno ocorrenciasField;
        
        private ItemRetornoEtiquetaInternacional[] itemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoEtiquetaInternacional[] itemRetorno {
            get {
                return this.itemRetornoField;
            }
            set {
                this.itemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorObjetoRetornoConsulta : TO {
        
        private string[] objetoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("objeto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] objeto {
            get {
                return this.objetoField;
            }
            set {
                this.objetoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class unitizadorRetornoConsulta : TO {
        
        private string codigoUnitizadorField;
        
        private AgrupadorObjetoRetornoConsulta objetosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoUnitizador {
            get {
                return this.codigoUnitizadorField;
            }
            set {
                this.codigoUnitizadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorObjetoRetornoConsulta objetos {
            get {
                return this.objetosField;
            }
            set {
                this.objetosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorUnitizadorRetornoConsulta : TO {
        
        private unitizadorRetornoConsulta[] unitizadorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("unitizador", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public unitizadorRetornoConsulta[] unitizador {
            get {
                return this.unitizadorField;
            }
            set {
                this.unitizadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class expedicaoRetornoConsulta : TO {
        
        private string numeroExpedicaoField;
        
        private AgrupadorUnitizadorRetornoConsulta unitizadoresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroExpedicao {
            get {
                return this.numeroExpedicaoField;
            }
            set {
                this.numeroExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorUnitizadorRetornoConsulta unitizadores {
            get {
                return this.unitizadoresField;
            }
            set {
                this.unitizadoresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorExpedicaoRetornoConsulta : TO {
        
        private expedicaoRetornoConsulta[] expedicaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("expedicao", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public expedicaoRetornoConsulta[] expedicao {
            get {
                return this.expedicaoField;
            }
            set {
                this.expedicaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class faturaEntregaRetornoConsulta : TO {
        
        private string codigoFaturaField;
        
        private AgrupadorExpedicaoRetornoConsulta expedicoesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoFatura {
            get {
                return this.codigoFaturaField;
            }
            set {
                this.codigoFaturaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorExpedicaoRetornoConsulta expedicoes {
            get {
                return this.expedicoesField;
            }
            set {
                this.expedicoesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorFaturaEntregaRetornoConsulta : TO {
        
        private faturaEntregaRetornoConsulta[] faturaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fatura", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public faturaEntregaRetornoConsulta[] fatura {
            get {
                return this.faturaField;
            }
            set {
                this.faturaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoConsultaFaturaEntregaTO : TO {
        
        private AgrupadorFaturaEntregaRetornoConsulta faturasField;
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorFaturaEntregaRetornoConsulta faturas {
            get {
                return this.faturasField;
            }
            set {
                this.faturasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemRetornoRestricaoProibicao : TO {
        
        private string codigoSHItemField;
        
        private string permissaoEntradaField;
        
        private string descricaoPermissaoEntradaField;
        
        private Retorno ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSHItem {
            get {
                return this.codigoSHItemField;
            }
            set {
                this.codigoSHItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string permissaoEntrada {
            get {
                return this.permissaoEntradaField;
            }
            set {
                this.permissaoEntradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoPermissaoEntrada {
            get {
                return this.descricaoPermissaoEntradaField;
            }
            set {
                this.descricaoPermissaoEntradaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoRestricaoProibicao : TO {
        
        private ItemRetornoRestricaoProibicao[] itemRetornoField;
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoRestricaoProibicao[] itemRetorno {
            get {
                return this.itemRetornoField;
            }
            set {
                this.itemRetornoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemEncomenda : TO {
        
        private string descricaoItemField;
        
        private string codigoSHItemField;
        
        private string codigoSKUItemField;
        
        private long quantidadeItemField;
        
        private bool quantidadeItemFieldSpecified;
        
        private double valorUnitarioField;
        
        private bool valorUnitarioFieldSpecified;
        
        private double pesoUnitarioField;
        
        private bool pesoUnitarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string descricaoItem {
            get {
                return this.descricaoItemField;
            }
            set {
                this.descricaoItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSHItem {
            get {
                return this.codigoSHItemField;
            }
            set {
                this.codigoSHItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoSKUItem {
            get {
                return this.codigoSKUItemField;
            }
            set {
                this.codigoSKUItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long quantidadeItem {
            get {
                return this.quantidadeItemField;
            }
            set {
                this.quantidadeItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quantidadeItemSpecified {
            get {
                return this.quantidadeItemFieldSpecified;
            }
            set {
                this.quantidadeItemFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorUnitario {
            get {
                return this.valorUnitarioField;
            }
            set {
                this.valorUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorUnitarioSpecified {
            get {
                return this.valorUnitarioFieldSpecified;
            }
            set {
                this.valorUnitarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pesoUnitario {
            get {
                return this.pesoUnitarioField;
            }
            set {
                this.pesoUnitarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoUnitarioSpecified {
            get {
                return this.pesoUnitarioFieldSpecified;
            }
            set {
                this.pesoUnitarioFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorItemEncomenda : TO {
        
        private ItemEncomenda[] itemEncomendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemEncomenda")]
        public ItemEncomenda[] itemEncomenda {
            get {
                return this.itemEncomendaField;
            }
            set {
                this.itemEncomendaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemRetornoConsultaEncomenda : TO {
        
        private string codigoObjetoField;
        
        private string codigoFaturaEntregaField;
        
        private int numeroExpedicaoField;
        
        private bool numeroExpedicaoFieldSpecified;
        
        private string codigoUnitizadorField;
        
        private string nomeRemetenteField;
        
        private string enderecoRemetenteField;
        
        private string numeroEnderecoRemetenteField;
        
        private string complementoEnderecoRemetenteField;
        
        private string codigoPostalRemetenteField;
        
        private string cidadeRemetenteField;
        
        private string estadoRemetenteField;
        
        private string paisRemetenteField;
        
        private string emailRemetenteField;
        
        private string telefoneRemetenteField;
        
        private string siteRemetenteField;
        
        private string nomeDestinatarioField;
        
        private string tipoDocumentoDestinatarioField;
        
        private string numeroDocumentoDestinatarioField;
        
        private string enderecoDestinatarioField;
        
        private string numeroEnderecoDestinatarioField;
        
        private string complementoEnderecoDestinatarioField;
        
        private string codigoPostalDestinatarioField;
        
        private string caixaPostalDestinatarioField;
        
        private string cidadeDestinatarioField;
        
        private string ufDestinatarioField;
        
        private string paisDestinatarioField;
        
        private string emailDestinatarioField;
        
        private string telefoneDestinatarioField;
        
        private double pesoObjetoField;
        
        private bool pesoObjetoFieldSpecified;
        
        private double comprimentoObjetoField;
        
        private bool comprimentoObjetoFieldSpecified;
        
        private double larguraObjetoField;
        
        private bool larguraObjetoFieldSpecified;
        
        private double alturaObjetoField;
        
        private bool alturaObjetoFieldSpecified;
        
        private long modalidadeDistribuicaoObjetoField;
        
        private bool modalidadeDistribuicaoObjetoFieldSpecified;
        
        private string modalidadePagamentoImpostosObjetoField;
        
        private string codigoMoedaField;
        
        private double valorFreteObjetoField;
        
        private bool valorFreteObjetoFieldSpecified;
        
        private double valorSeguroObjetoField;
        
        private bool valorSeguroObjetoFieldSpecified;
        
        private long modoDevolucaoObjetoField;
        
        private bool modoDevolucaoObjetoFieldSpecified;
        
        private string seguroDevolucaoObjetoField;
        
        private AgrupadorItemEncomenda itensEncomendaField;
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoObjeto {
            get {
                return this.codigoObjetoField;
            }
            set {
                this.codigoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoFaturaEntrega {
            get {
                return this.codigoFaturaEntregaField;
            }
            set {
                this.codigoFaturaEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int numeroExpedicao {
            get {
                return this.numeroExpedicaoField;
            }
            set {
                this.numeroExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numeroExpedicaoSpecified {
            get {
                return this.numeroExpedicaoFieldSpecified;
            }
            set {
                this.numeroExpedicaoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoUnitizador {
            get {
                return this.codigoUnitizadorField;
            }
            set {
                this.codigoUnitizadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeRemetente {
            get {
                return this.nomeRemetenteField;
            }
            set {
                this.nomeRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enderecoRemetente {
            get {
                return this.enderecoRemetenteField;
            }
            set {
                this.enderecoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroEnderecoRemetente {
            get {
                return this.numeroEnderecoRemetenteField;
            }
            set {
                this.numeroEnderecoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string complementoEnderecoRemetente {
            get {
                return this.complementoEnderecoRemetenteField;
            }
            set {
                this.complementoEnderecoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPostalRemetente {
            get {
                return this.codigoPostalRemetenteField;
            }
            set {
                this.codigoPostalRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeRemetente {
            get {
                return this.cidadeRemetenteField;
            }
            set {
                this.cidadeRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string estadoRemetente {
            get {
                return this.estadoRemetenteField;
            }
            set {
                this.estadoRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paisRemetente {
            get {
                return this.paisRemetenteField;
            }
            set {
                this.paisRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailRemetente {
            get {
                return this.emailRemetenteField;
            }
            set {
                this.emailRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefoneRemetente {
            get {
                return this.telefoneRemetenteField;
            }
            set {
                this.telefoneRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string siteRemetente {
            get {
                return this.siteRemetenteField;
            }
            set {
                this.siteRemetenteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nomeDestinatario {
            get {
                return this.nomeDestinatarioField;
            }
            set {
                this.nomeDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tipoDocumentoDestinatario {
            get {
                return this.tipoDocumentoDestinatarioField;
            }
            set {
                this.tipoDocumentoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroDocumentoDestinatario {
            get {
                return this.numeroDocumentoDestinatarioField;
            }
            set {
                this.numeroDocumentoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string enderecoDestinatario {
            get {
                return this.enderecoDestinatarioField;
            }
            set {
                this.enderecoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroEnderecoDestinatario {
            get {
                return this.numeroEnderecoDestinatarioField;
            }
            set {
                this.numeroEnderecoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string complementoEnderecoDestinatario {
            get {
                return this.complementoEnderecoDestinatarioField;
            }
            set {
                this.complementoEnderecoDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoPostalDestinatario {
            get {
                return this.codigoPostalDestinatarioField;
            }
            set {
                this.codigoPostalDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string caixaPostalDestinatario {
            get {
                return this.caixaPostalDestinatarioField;
            }
            set {
                this.caixaPostalDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cidadeDestinatario {
            get {
                return this.cidadeDestinatarioField;
            }
            set {
                this.cidadeDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ufDestinatario {
            get {
                return this.ufDestinatarioField;
            }
            set {
                this.ufDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string paisDestinatario {
            get {
                return this.paisDestinatarioField;
            }
            set {
                this.paisDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string emailDestinatario {
            get {
                return this.emailDestinatarioField;
            }
            set {
                this.emailDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string telefoneDestinatario {
            get {
                return this.telefoneDestinatarioField;
            }
            set {
                this.telefoneDestinatarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double pesoObjeto {
            get {
                return this.pesoObjetoField;
            }
            set {
                this.pesoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pesoObjetoSpecified {
            get {
                return this.pesoObjetoFieldSpecified;
            }
            set {
                this.pesoObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double comprimentoObjeto {
            get {
                return this.comprimentoObjetoField;
            }
            set {
                this.comprimentoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool comprimentoObjetoSpecified {
            get {
                return this.comprimentoObjetoFieldSpecified;
            }
            set {
                this.comprimentoObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double larguraObjeto {
            get {
                return this.larguraObjetoField;
            }
            set {
                this.larguraObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool larguraObjetoSpecified {
            get {
                return this.larguraObjetoFieldSpecified;
            }
            set {
                this.larguraObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double alturaObjeto {
            get {
                return this.alturaObjetoField;
            }
            set {
                this.alturaObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alturaObjetoSpecified {
            get {
                return this.alturaObjetoFieldSpecified;
            }
            set {
                this.alturaObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long modalidadeDistribuicaoObjeto {
            get {
                return this.modalidadeDistribuicaoObjetoField;
            }
            set {
                this.modalidadeDistribuicaoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modalidadeDistribuicaoObjetoSpecified {
            get {
                return this.modalidadeDistribuicaoObjetoFieldSpecified;
            }
            set {
                this.modalidadeDistribuicaoObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modalidadePagamentoImpostosObjeto {
            get {
                return this.modalidadePagamentoImpostosObjetoField;
            }
            set {
                this.modalidadePagamentoImpostosObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoMoeda {
            get {
                return this.codigoMoedaField;
            }
            set {
                this.codigoMoedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorFreteObjeto {
            get {
                return this.valorFreteObjetoField;
            }
            set {
                this.valorFreteObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorFreteObjetoSpecified {
            get {
                return this.valorFreteObjetoFieldSpecified;
            }
            set {
                this.valorFreteObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double valorSeguroObjeto {
            get {
                return this.valorSeguroObjetoField;
            }
            set {
                this.valorSeguroObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valorSeguroObjetoSpecified {
            get {
                return this.valorSeguroObjetoFieldSpecified;
            }
            set {
                this.valorSeguroObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public long modoDevolucaoObjeto {
            get {
                return this.modoDevolucaoObjetoField;
            }
            set {
                this.modoDevolucaoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool modoDevolucaoObjetoSpecified {
            get {
                return this.modoDevolucaoObjetoFieldSpecified;
            }
            set {
                this.modoDevolucaoObjetoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string seguroDevolucaoObjeto {
            get {
                return this.seguroDevolucaoObjetoField;
            }
            set {
                this.seguroDevolucaoObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorItemEncomenda itensEncomenda {
            get {
                return this.itensEncomendaField;
            }
            set {
                this.itensEncomendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class AgrupadorItemRetornoConsultaEncomenda : TO {
        
        private ItemRetornoConsultaEncomenda[] encomendaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("encomenda", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoConsultaEncomenda[] encomenda {
            get {
                return this.encomendaField;
            }
            set {
                this.encomendaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoConsultaEncomenda : TO {
        
        private Retorno ocorrenciasField;
        
        private AgrupadorItemRetornoConsultaEncomenda encomendasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public AgrupadorItemRetornoConsultaEncomenda encomendas {
            get {
                return this.encomendasField;
            }
            set {
                this.encomendasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoCodigoFatura : TO {
        
        private string codigoFaturaEntregaField;
        
        private string valorSaldoField;
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoFaturaEntrega {
            get {
                return this.codigoFaturaEntregaField;
            }
            set {
                this.codigoFaturaEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string valorSaldo {
            get {
                return this.valorSaldoField;
            }
            set {
                this.valorSaldoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoConsultaUnitizador : TO {
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        private ItemRetornoConsultaUnitizador[] itemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoConsultaUnitizador[] itemRetorno {
            get {
                return this.itemRetornoField;
            }
            set {
                this.itemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class ItemRetornoConsultaUnitizador : TO {
        
        private string codigoUnitizadorField;
        
        private string numeroExpedicaoField;
        
        private string codigoFaturaEntregaField;
        
        private string[] codigosObjetoField;
        
        private Retorno ocorrenciasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoUnitizador {
            get {
                return this.codigoUnitizadorField;
            }
            set {
                this.codigoUnitizadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string numeroExpedicao {
            get {
                return this.numeroExpedicaoField;
            }
            set {
                this.numeroExpedicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string codigoFaturaEntrega {
            get {
                return this.codigoFaturaEntregaField;
            }
            set {
                this.codigoFaturaEntregaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("codigosObjeto", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] codigosObjeto {
            get {
                return this.codigosObjetoField;
            }
            set {
                this.codigosObjetoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://service.edei.correios.com.br/")]
    public partial class RetornoCancelarRotuloUnitizador : TO {
        
        private Retorno ocorrenciasField;
        
        private string versaoField;
        
        private ItemRetornoConsultaUnitizador[] itemRetornoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Retorno ocorrencias {
            get {
                return this.ocorrenciasField;
            }
            set {
                this.ocorrenciasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string versao {
            get {
                return this.versaoField;
            }
            set {
                this.versaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("itemRetorno", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ItemRetornoConsultaUnitizador[] itemRetorno {
            get {
                return this.itemRetornoField;
            }
            set {
                this.itemRetornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void solicitarSaldoClienteCompletedEventHandler(object sender, solicitarSaldoClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarSaldoClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarSaldoClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoSaldo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoSaldo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void cancelarRotuloUnitizadorCompletedEventHandler(object sender, cancelarRotuloUnitizadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class cancelarRotuloUnitizadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal cancelarRotuloUnitizadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoCancelarRotuloUnitizador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoCancelarRotuloUnitizador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultarUnitizadorCompletedEventHandler(object sender, consultarUnitizadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarUnitizadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarUnitizadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoConsultaUnitizador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoConsultaUnitizador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void solicitarCodigoFaturaCompletedEventHandler(object sender, solicitarCodigoFaturaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarCodigoFaturaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarCodigoFaturaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoCodigoFatura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoCodigoFatura)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultarEncomendaCompletedEventHandler(object sender, consultarEncomendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarEncomendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarEncomendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoConsultaEncomenda Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoConsultaEncomenda)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultarRestricaoProibicaoItemCompletedEventHandler(object sender, consultarRestricaoProibicaoItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultarRestricaoProibicaoItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultarRestricaoProibicaoItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoRestricaoProibicao Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoRestricaoProibicao)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void consultaFaturaEntregaCompletedEventHandler(object sender, consultaFaturaEntregaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class consultaFaturaEntregaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal consultaFaturaEntregaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoConsultaFaturaEntregaTO Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoConsultaFaturaEntregaTO)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void getVersaoCompletedEventHandler(object sender, getVersaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getVersaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getVersaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void solicitarCodigoEtiquetaInternacionalCompletedEventHandler(object sender, solicitarCodigoEtiquetaInternacionalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarCodigoEtiquetaInternacionalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarCodigoEtiquetaInternacionalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoEtiquetaInternacional Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoEtiquetaInternacional)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void solicitarRotuloUnitizadorCompletedEventHandler(object sender, solicitarRotuloUnitizadorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class solicitarRotuloUnitizadorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal solicitarRotuloUnitizadorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RetornoRotuloUnitizador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RetornoRotuloUnitizador)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591